### ISSUE TITLE
Accessing other getters with TypeScript

### ISSUE THREAD

**Issue by Grawl** [TobyMosque/quasar-v2-ssr-pinia#5]
This issue is targeting ability to access other store getters from getter using `this`: https://pinia.vuejs.org/core-concepts/getters.html#accessing-other-getters

Demo store:

```ts
export const useFoo = defineStore('foo', {
  state: () => ({
    text: '',
    toggle: false,
  }),
  getters: {
    reversedText(store) {
      return store.text.split('').reverse().join('')
    },
    helloText() {
      return 'Hello ' + this.reversedText
    },
    textOrReversed(store) {
      return store.toggle ? store.text : this.reversedText
    },
  },
});
```

Got an error:

```
TS2339: Property 'reversedText' does not exist on type '{ text: string; toggle: boolean; } & _StoreWithGetters{}> & PiniaCustomProperties  , _ActionsTree>'.
```

I see if I set `store` as getter first argument, `this` is not working.

**Comment by TobyMosque** [comment]
that is a know limitation of the pinia/ts, u can't use `this` and pass the `state` as a parameter at the same time.

https://pinia.vuejs.org/core-concepts/getters.html

> Most of the time, getters will only rely on the state, however, they might need to use other getters. Because of this, we can get access to the *whole store instance* through `this` when defining a regular function **but it is necessary to define the type of the return type (in TypeScript)**. This is due to a known limitation in TypeScript and **doesn't affect getters defined with an arrow function nor getters not using `this`**:

```js
export const useFoo = defineStore('foo', {
  state: () => ({
    text: '',
    toggle: false,
  }),
  getters: {
    reversedText(store) {
      return store.text.split('').reverse().join('')
    },
    helloText() {
      return 'Hello ' + this.reversedText
    },
    textOrReversed(): string {
      return this.toggle ? this.text : this.reversedText
    },
  },
});
```

**Comment by Grawl** [comment]
Thank you!
